title: Computing with AI
author: Arnold Ip
email: arnold.hn.ip@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A practice blog recording the thoughts of AI.

# social links
twitter_username: hiro_ip
github_username:  hirokuzu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
